# Generated by CMake 2.8.2

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target openjp2
ADD_LIBRARY(openjp2 SHARED IMPORTED)

# Create imported target openjpwl
ADD_LIBRARY(openjpwl SHARED IMPORTED)

# Create imported target openjpip
ADD_LIBRARY(openjpip SHARED IMPORTED)

# Create imported target opj_decompress
ADD_EXECUTABLE(opj_decompress IMPORTED)

# Create imported target opj_compress
ADD_EXECUTABLE(opj_compress IMPORTED)

# Create imported target opj_dump
ADD_EXECUTABLE(opj_dump IMPORTED)

# Create imported target opj_jpip_addxml
ADD_EXECUTABLE(opj_jpip_addxml IMPORTED)

# Create imported target opj_dec_server
ADD_EXECUTABLE(opj_dec_server IMPORTED)

# Create imported target opj_jpip_transcode
ADD_EXECUTABLE(opj_jpip_transcode IMPORTED)

# Create imported target opj_jpip_test
ADD_EXECUTABLE(opj_jpip_test IMPORTED)

# Load information for each installed configuration.
GET_FILENAME_COMPONENT(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
FILE(GLOB CONFIG_FILES "${_DIR}/OpenJPEGTargets-*.cmake")
FOREACH(f ${CONFIG_FILES})
  INCLUDE(${f})
ENDFOREACH(f)

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
